### ISSUE TITLE
General Code Review & Cleanup

### ISSUE THREAD

**Issue by artistro08** [artistro08/tailor-starter#12]
The code here is good, but some of the code does not follow consistent naming conventions. The aim here is to clean up the code and release it in a minor release. 

## TODO
- [x] Check all files for naming conventions
- [x] Rename and update the template links accordingly
- [x] Double check consistency throughout the site
- [x] Publish as a minor release

**Comment by artistro08** [comment]
fixed in v3.1.0
